services:
  - type: web
    name: indian-food-classification
    env: python
    buildCommand: bash bin/build.sh
    startCommand: bash bin/start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
