services:
  - type: web
    name: indian-food-classification
    env: python
    buildCommand: git lfs install && git lfs pull && pip install -r requirements.txt
    startCommand: bash bin/start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.9
